# Generated by Django 5.0.1 on 2026-02-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deployment_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
